### ISSUE TITLE
Error while try to create AuthorizationRequest. self is not defined.

### ISSUE THREAD

**Issue by maximussJS** [upcecconnect/PythonSDK#1]
```
from upcpayment import Upc_payment_xml

payment = Upc_payment_xml.AuthorizationRequest(
    merchant_id='merchant_id',
    terminal_id='terminal_id',
    order_id='order_id',
    date='date',
    total_amount='total_amount',
    currency='currency',
    purchase_desc='test',
    card_num='1234123412341234',
    exp_year='exp_year',
    exp_month='exp_month',
    cv_num='cv_num',
    status='status',
    cavv='cavv',
    eci='eci',
    cavv_alg='cavv_alg'
 )
xml = p.generate_xml_with_signature(pk)

```
This code was taken from your [docs](https://pypi.org/project/upcpayment/).
And it raise an error.
```
Traceback (most recent call last):
  File "index.py", line 32, in <module>
    xml = p.generate_xml_with_signature(pk)
  File "/home/user/.local/lib/python3.8/site-packages/upcpayment/Upc_payment_xml.py", line 228, in generate_xml_with_signature
    _add_card_with_data(PayData, self.card_num, self.exp_year, self.exp_month, self.cv_num, '')
  File "/home/user/.local/lib/python3.8/site-packages/upcpayment/Upc_payment_xml.py", line 66, in _add_card_with_data
    CardNum.text = self.card_num
NameError: name 'self' is not defined
```
FIle `Upc_payment_xml.py`
Function  `_add_card_with_data` uses `self`.
self is the self-reference in a Class. Your code is not in a class, you only have functions defined. You have to wrap your methods in a class,`
```
def _add_card_with_data(parent_element, card_num, exp_year, exp_month, cv_num, tavv): 
   Card = etree.SubElement(parent_element, 'Card')
   CardNum = etree.SubElement(Card, 'CardNum')
   CardNum.text =  self.card_num 
   ExpYear = etree.SubElement(Card, 'ExpYear')
   ExpYear.text = self.exp_year  
   ExpMonth = etree.SubElement(Card, 'ExpMonth')
   ExpMonth.text = self.exp_month    
   if cv_num:  
       CVNum = etree.SubElement(Card, 'CVNum')   
       CVNum.text = self.cv_num   
   if tavv:  
       ExtDataToken = etree.SubElement(Card, 'ExtDataToken')
       TAVV = etree.SubElement(ExtDataToken, 'TAVV')     
       TAVV.text = tavv<br class="Apple-interchange-newline">`
```

Fix it please.

**Comment by upcecconnect** [comment]
Thanks for your reply. Fixed.
